package com.finsurge.tmr_portal.mx_superview.models;

public enum UAMReportType {
    COMBINED_PORTFOLIO,
    NAVIGATION_RIGHTS,
    OSP_RIGHTS,
    STP_RIGHTS,
    CONSISTENCY_TEMPLATE,
    CHINESE_WALL_DEFINITIONS,
    PORTFOLIO_RIGHTS,
    OPERATION_RIGHTS,
    FINANCE_RIGHTS,
    CONFIGURATION_MANAGEMENT_RIGHTS,
    ENTERPRISE_RISK_MANAGEMENT,
//    AUDIT_BODY_REPORT,
//    AUDIT_HEADER_REPORT,
//    USER_LIST,
//    COUNTERPARTY_DISPLAY,
//    COUNTERPARTY_TEMPLATE
}
